### PR TITLE
Added INSTALL.md to the root directory of the project

### PR DESCRIPTION
**Pull request by derickso8**
Added Install document with directions on how to install the dependencies and run the project.

### CODE REVIEW

**Comment by SuprajaKalva** [comment]
This looks great David! The instructions look great! You can continue with the merge.

**Comment by NickJGG** [comment]
Looks good - all the instructions for installation are there.

**Comment by Aadamko1** [comment]
Looks like you covered everything required for installation, good job

**Comment by ghost** [comment]
I find this document needs a warning about SQLITE needing to be installed.

**Comment by sjiang1** [comment]
> I find this document needs a warning about SQLITE needing to be installed.

it's a good one! I am a little bit confused myself. I tried to follow your Installation documentation, and I needed to install Sqlite. But when I search online, some say that Python3 has sqlite3 included. Did you need to install sqlite3 explicitly when you set up your project?

@derickso8 @SuprajaKalva @NickJGG @Aadamko1 @aschuma5

**Pull request merged**
